### ISSUE TITLE
Query on the libraries used in harness.io

### ISSUE THREAD

**Issue by vgs18** [harness/developer-hub#1053]
# Harness Developer Hub Issue/Feature Request
Thanks for helping us make the Developer Hub better. Feel free to use GitHub Issues for reporting issues or requesting features. 

## Is this an Issue or Feature?

- [ ] Issue
- [ ] Feature
- [✅] Query

## If Issue, Tell Us a Little More

Hi, this is not a feature request or a bug report, wanted to understand the what type of charts are used in harness.io and which libraries are used for harness charts visualisations. Few details on those lines and the licence details will be helpful. Thanks in advance.

### Typo?
Typos are bound to happen. The quickest way to fix, submit a PR or let us know. 

## If Feature, What Would You Like to See

Please replace this line with a brief summary of your idea/feature request.

**Comment by ravilach** [comment]
Hey @vgs18 thanks for the inquiry. Are you asking about charts that are on developer.harness.io or the product, Harness? For developer.harness.io we use Mermaid Charts - https://mermaid.js.org/

**Comment by ravilach** [comment]
As for our product, can take a look at one of the Open Source renditions -> https://github.com/harness/harness-cd-community

**Comment by vgs18** [comment]
Hi @ravilach, Thanks for the clarification. I was looking for the charts that are used in developer.harness.io. This was helpful. Thanks!!
