### ISSUE TITLE
A service instance is not a count of instances

### ISSUE THREAD

**Issue by mcascone** [harness/developer-hub#2097]
Something doesn't seem right in this sentence:

> A Service Instance is the number of running Service instances at any given moment

The second part of the sentence appears closer to the truth:

>  (pods in case of Kubernetes, hosts in case of SSH-based deployments, etc).

Especially because this is how licenses are billed, this seems like a detail that should be re-defined to be very clear.

https://github.com/harness/developer-hub/blob/0323f9d1ed898d1480ef91cafbb7e89f9cba3be1/docs/continuous-delivery/get-started/cd-pipeline-basics.md?plain=1#L68

**Comment by ravilach** [comment]
@michaelcretzman can you take a look please. Thanks!

**Comment by ravilach** [comment]
@michaelcretzman any feedback?

**Comment by michaelcretzman** [comment]
@ravilach no. 

@mcascone can you clarify what "doesn't seem right in this sentence", please? A service instance is the number of running Harness Service instances. If your Service is K8s, it's pods.

**Comment by ravilach** [comment]
@mcascone any additional feedback. @michaelcretzman we can close this issue if we don't see an area for improvement.

**Comment by mcascone** [comment]
The term is being used to describe itself, and also as a count:

> A service instance is the number of service instances.

Describing a thing as the count of itself is pretty confusing, at least to me.

**Comment by schoudhury** [comment]
thanks for reporting this issue. it has been fixed. you can see the latest here: https://developer.harness.io/docs/continuous-delivery/get-started/key-concepts#service-instance
