### ISSUE TITLE
Troubleshooting guide for CCM not available

### ISSUE THREAD

**Issue by withshubh** [harness/developer-hub#4123]
# Harness Developer Hub Issue/Feature Request
Thanks for helping us make the Developer Hub better. Feel free to use GitHub Issues for reporting issues or requesting features. 

## Is this an Issue or Feature?

- [x] Issue
- [ ] Feature

## If Issue, Tell Us a Little More

Currently, the troubleshooting guide shows `KB coming soon`. It is suggested to remove the page or make it inaccessible by hiding it from the sidebar.

Link: https://developer.harness.io/kb/cloud-cost-management/articles/troubleshooting-guide

Would be happy to fix this by raising a PR.

**Comment by ravilach** [comment]
@withshubh thanks for bringing this to our attention. @deepanshuHarness we had some place-holder pages before we had pages to support the navigation. For items that have more than one child element, we can just remove. 

<img width="1183" alt="image" src="https://github.com/harness/developer-hub/assets/42775804/a4f96da7-115a-42dc-995a-f8240eaa7d9f">

**Comment by ravilach** [comment]
https://github.com/harness/developer-hub/pull/4187

**Comment by ravilach** [comment]
Merged.
