### ISSUE TITLE
EKS SMP use gp3 storageClass

### ISSUE THREAD

**Issue by tuffacton** [harness/developer-hub#6569]
Thanks for contributing to the Harness Developer Hub! Please use GitHub Issues to report documentation issues or request documentation enhancements, and our code owners will review your issue.

**For issues and feature requests for the Harness Platform and modules, use the [Harness Ideas Portal](https://ideas.harness.io/).**

## Type

- [ ] Issue (such as typos, broken images/links, or missing/malformed documentation)
- [X] Enhancement (such as UX suggestions, new documentation requests, or suggestions for how content is organized/presented)

> :bulb: **Tip:** You can select **Edit this Page** at the bottom of any HDH page to instantly edit that page and submit a PR. This is the fastest way to correct errors and publish other small changes.

## Description

As we described internally, want to provide more context for our EKS SMP install to utilize gp3 storage class as the default to help users save money: 
> No, we have a placeholder for storageClassName, if it is unspecified it picks up the cluster’s default storageclass (which is usually gp2 in aws, standard in gcp, it differs if customer has explicitly set it different as well)
> you can make the storageClass configurable by setting global.storageClassName and global.storageClass to both gp3 in your onverride files. If there is a storageclass with that name, it will assign it to that

@tuffacton will take it on, just wanted the ticket started

**Comment by ravilach** [comment]
@tuffacton can we close this?

**Comment by tuffacton** [comment]
Yes, lets clean it up, I'll get a proper ticket if it comes up
