### ISSUE TITLE
Consolidate User Profiles and Reference Architectures

### ISSUE THREAD

**Issue by tuffacton** [harness/developer-hub#6818]
Thanks for contributing to the Harness Developer Hub! Please use GitHub Issues to report documentation issues or request documentation enhancements, and our code owners will review your issue.

**For issues and feature requests for the Harness Platform and modules, use the [Harness Ideas Portal](https://ideas.harness.io/).**

## Type

- [ ] Issue (such as typos, broken images/links, or missing/malformed documentation)
- [X] Enhancement (such as UX suggestions, new documentation requests, or suggestions for how content is organized/presented)

> :bulb: **Tip:** You can select **Edit this Page** at the bottom of any HDH page to instantly edit that page and submit a PR. This is the fastest way to correct errors and publish other small changes.

## Description

From my perspective there is going to be confusion around https://developer.harness.io/docs/self-managed-enterprise-edition/user-profiles and https://developer.harness.io/docs/self-managed-enterprise-edition/advanced-configurations/reference-architecture. Can we select one page and consolidate?

**Comment by brian-f-harness** [comment]
@tuffacton I created a ticket to track this work.
https://harness.atlassian.net/browse/PL-51451
